//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtobufDecoder.Application.Wpf {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProtobufDecoder.Application.Wpf.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Acknowledgements: 的本地化字符串。
        /// </summary>
        public static string AboutAcknowledgements {
            get {
                return ResourceManager.GetString("AboutAcknowledgements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Close 的本地化字符串。
        /// </summary>
        public static string AboutButtonClose {
            get {
                return ResourceManager.GetString("AboutButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License: 的本地化字符串。
        /// </summary>
        public static string AboutLicense {
            get {
                return ResourceManager.GetString("AboutLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sources: 的本地化字符串。
        /// </summary>
        public static string AboutSources {
            get {
                return ResourceManager.GetString("AboutSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About Protobuf Decoder 的本地化字符串。
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version: 的本地化字符串。
        /// </summary>
        public static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot decode selected tag 的本地化字符串。
        /// </summary>
        public static string CannotDecodeTag {
            get {
                return ResourceManager.GetString("CannotDecodeTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clipboard did not contain any bytes to load 的本地化字符串。
        /// </summary>
        public static string ClipboardEmpty {
            get {
                return ResourceManager.GetString("ClipboardEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Common 的本地化字符串。
        /// </summary>
        public static string CommonTagProperties {
            get {
                return ResourceManager.GetString("CommonTagProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy value as C# bytes 的本地化字符串。
        /// </summary>
        public static string ContextMenuCopyValue {
            get {
                return ResourceManager.GetString("ContextMenuCopyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decode all tags 的本地化字符串。
        /// </summary>
        public static string ContextMenuDecodeAllTags {
            get {
                return ResourceManager.GetString("ContextMenuDecodeAllTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Decode tag 的本地化字符串。
        /// </summary>
        public static string ContextMenuDecodeTag {
            get {
                return ResourceManager.GetString("ContextMenuDecodeTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decoding tag failed: {0} 的本地化字符串。
        /// </summary>
        public static string FailedToDecodeTag {
            get {
                return ResourceManager.GetString("FailedToDecodeTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File failed to load: {0} 的本地化字符串。
        /// </summary>
        public static string FileFailedToLoad {
            get {
                return ResourceManager.GetString("FileFailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File has a {0}-byte length prefix which was stripped 的本地化字符串。
        /// </summary>
        public static string FileLengthPrefix {
            get {
                return ResourceManager.GetString("FileLengthPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File loaded successfully 的本地化字符串。
        /// </summary>
        public static string FileLoadedSuccessfully {
            get {
                return ResourceManager.GetString("FileLoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File loaded successfully: {0} 的本地化字符串。
        /// </summary>
        public static string FileLoadedWithWarnings {
            get {
                return ResourceManager.GetString("FileLoadedWithWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameters 的本地化字符串。
        /// </summary>
        public static string InputCaption {
            get {
                return ResourceManager.GetString("InputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please check the path to the input file 的本地化字符串。
        /// </summary>
        public static string InputFileDoesNotExist_Text {
            get {
                return ResourceManager.GetString("InputFileDoesNotExist_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input is either empty or contains only newlines, spaces etc 的本地化字符串。
        /// </summary>
        public static string InputIsEmpty {
            get {
                return ResourceManager.GetString("InputIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input appears not to be valid base-64 : {0} 的本地化字符串。
        /// </summary>
        public static string InputIsNotBase64 {
            get {
                return ResourceManager.GetString("InputIsNotBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input file: 的本地化字符串。
        /// </summary>
        public static string InputSourcePath {
            get {
                return ResourceManager.GetString("InputSourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Base64 input with and without padding is supported.
        ///Newlines, spaces and double quotes are automatically removed. 的本地化字符串。
        /// </summary>
        public static string LoadBase64Instruction {
            get {
                return ResourceManager.GetString("LoadBase64Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load Base64 string 的本地化字符串。
        /// </summary>
        public static string LoadBase64StringTitle {
            get {
                return ResourceManager.GetString("LoadBase64StringTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Load 的本地化字符串。
        /// </summary>
        public static string LoadButton {
            get {
                return ResourceManager.GetString("LoadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supported formats: 
        ///- 0x00 0x01
        ///- 0x0001
        ///- \x00\x01
        ///Newlines, spaces and double quotes are automatically removed. 的本地化字符串。
        /// </summary>
        public static string LoadHexStreamInstruction {
            get {
                return ResourceManager.GetString("LoadHexStreamInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load hex stream 的本地化字符串。
        /// </summary>
        public static string LoadHexStringTitle {
            get {
                return ResourceManager.GetString("LoadHexStringTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _File 的本地化字符串。
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E_xit 的本地化字符串。
        /// </summary>
        public static string MenuFileExit {
            get {
                return ResourceManager.GetString("MenuFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _New window 的本地化字符串。
        /// </summary>
        public static string MenuFileNewWindow {
            get {
                return ResourceManager.GetString("MenuFileNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Open 的本地化字符串。
        /// </summary>
        public static string MenuFileOpen {
            get {
                return ResourceManager.GetString("MenuFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Save proto file 的本地化字符串。
        /// </summary>
        public static string MenuFileSaveGeneratedProto {
            get {
                return ResourceManager.GetString("MenuFileSaveGeneratedProto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save proto file _As... 的本地化字符串。
        /// </summary>
        public static string MenuFileSaveGeneratedProtoAs {
            get {
                return ResourceManager.GetString("MenuFileSaveGeneratedProtoAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Help 的本地化字符串。
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _About 的本地化字符串。
        /// </summary>
        public static string MenuHelpAbout {
            get {
                return ResourceManager.GetString("MenuHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load from Base64 string 的本地化字符串。
        /// </summary>
        public static string MenuLoadFromBase64String {
            get {
                return ResourceManager.GetString("MenuLoadFromBase64String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load from clipboard 的本地化字符串。
        /// </summary>
        public static string MenuLoadFromClipboard {
            get {
                return ResourceManager.GetString("MenuLoadFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load from hex stream 的本地化字符串。
        /// </summary>
        public static string MenuLoadFromHexStream {
            get {
                return ResourceManager.GetString("MenuLoadFromHexStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to save proto file: {0} 的本地化字符串。
        /// </summary>
        public static string ProtoFileFailedToSave {
            get {
                return ResourceManager.GetString("ProtoFileFailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proto file saved as: {0} 的本地化字符串。
        /// </summary>
        public static string ProtoFileSavedAs {
            get {
                return ResourceManager.GetString("ProtoFileSavedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proto file saved 的本地化字符串。
        /// </summary>
        public static string ProtoFileSavedSuccessfully {
            get {
                return ResourceManager.GetString("ProtoFileSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protobuf files (.proto)|*.proto 的本地化字符串。
        /// </summary>
        public static string ProtoFileType {
            get {
                return ResourceManager.GetString("ProtoFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready 的本地化字符串。
        /// </summary>
        public static string StatusBarReadyText {
            get {
                return ResourceManager.GetString("StatusBarReadyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag value copied to clipboard 的本地化字符串。
        /// </summary>
        public static string TagCopiedToClipboard {
            get {
                return ResourceManager.GetString("TagCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag decoded successfully 的本地化字符串。
        /// </summary>
        public static string TagDecodedSuccessfully {
            get {
                return ResourceManager.GetString("TagDecodedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string TagPropertiesName {
            get {
                return ResourceManager.GetString("TagPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        public static string TagPropertiesValue {
            get {
                return ResourceManager.GetString("TagPropertiesValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (repeated) 的本地化字符串。
        /// </summary>
        public static string TagRepeated {
            get {
                return ResourceManager.GetString("TagRepeated", resourceCulture);
            }
        }
    }
}
