//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtobufDecoder.Application.Wpf {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProtobufDecoder.Application.Wpf.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string AboutButtonClose {
            get {
                return ResourceManager.GetString("AboutButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Protobuf Decoder.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot decode selected tag.
        /// </summary>
        public static string CannotDecodeTag {
            get {
                return ResourceManager.GetString("CannotDecodeTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard did not contain any bytes to load.
        /// </summary>
        public static string ClipboardEmpty {
            get {
                return ResourceManager.GetString("ClipboardEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string CommonTagProperties {
            get {
                return ResourceManager.GetString("CommonTagProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy value as C# bytes.
        /// </summary>
        public static string ContextMenuCopyValue {
            get {
                return ResourceManager.GetString("ContextMenuCopyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode all tags.
        /// </summary>
        public static string ContextMenuDecodeAllTags {
            get {
                return ResourceManager.GetString("ContextMenuDecodeAllTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Decode tag.
        /// </summary>
        public static string ContextMenuDecodeTag {
            get {
                return ResourceManager.GetString("ContextMenuDecodeTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoding tag failed: {0}.
        /// </summary>
        public static string FailedToDecodeTag {
            get {
                return ResourceManager.GetString("FailedToDecodeTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File failed to load: {0}.
        /// </summary>
        public static string FileFailedToLoad {
            get {
                return ResourceManager.GetString("FileFailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has a {0}-byte length prefix which was stripped.
        /// </summary>
        public static string FileLengthPrefix {
            get {
                return ResourceManager.GetString("FileLengthPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File loaded successfully.
        /// </summary>
        public static string FileLoadedSuccessfully {
            get {
                return ResourceManager.GetString("FileLoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File loaded successfully: {0}.
        /// </summary>
        public static string FileLoadedWithWarnings {
            get {
                return ResourceManager.GetString("FileLoadedWithWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string InputCaption {
            get {
                return ResourceManager.GetString("InputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the path to the input file.
        /// </summary>
        public static string InputFileDoesNotExist_Text {
            get {
                return ResourceManager.GetString("InputFileDoesNotExist_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file:.
        /// </summary>
        public static string InputSourcePath {
            get {
                return ResourceManager.GetString("InputSourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string MenuFileExit {
            get {
                return ResourceManager.GetString("MenuFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string MenuFileOpen {
            get {
                return ResourceManager.GetString("MenuFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save proto file.
        /// </summary>
        public static string MenuFileSaveGeneratedProto {
            get {
                return ResourceManager.GetString("MenuFileSaveGeneratedProto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save proto file _As....
        /// </summary>
        public static string MenuFileSaveGeneratedProtoAs {
            get {
                return ResourceManager.GetString("MenuFileSaveGeneratedProtoAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string MenuHelpAbout {
            get {
                return ResourceManager.GetString("MenuHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load from clipboard.
        /// </summary>
        public static string MenuLoadFromClipboard {
            get {
                return ResourceManager.GetString("MenuLoadFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save proto file: {0}.
        /// </summary>
        public static string ProtoFileFailedToSave {
            get {
                return ResourceManager.GetString("ProtoFileFailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proto file saved as: {0}.
        /// </summary>
        public static string ProtoFileSavedAs {
            get {
                return ResourceManager.GetString("ProtoFileSavedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proto file saved.
        /// </summary>
        public static string ProtoFileSavedSuccessfully {
            get {
                return ResourceManager.GetString("ProtoFileSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protobuf files (.proto)|*.proto.
        /// </summary>
        public static string ProtoFileType {
            get {
                return ResourceManager.GetString("ProtoFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string StatusBarReadyText {
            get {
                return ResourceManager.GetString("StatusBarReadyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag value copied to clipboard.
        /// </summary>
        public static string TagCopiedToClipboard {
            get {
                return ResourceManager.GetString("TagCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag decoded successfully.
        /// </summary>
        public static string TagDecodedSuccessfully {
            get {
                return ResourceManager.GetString("TagDecodedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TagPropertiesName {
            get {
                return ResourceManager.GetString("TagPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string TagPropertiesValue {
            get {
                return ResourceManager.GetString("TagPropertiesValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (repeated).
        /// </summary>
        public static string TagRepeated {
            get {
                return ResourceManager.GetString("TagRepeated", resourceCulture);
            }
        }
    }
}
